#################################### common config : ####################################
spring:
  profiles:
    active: dev
  application:
    name: minzuchess-spring-boot
#    静态资源
  resources:
    static-locations: classpath:/static/
# mail:
  mail:
    host: smtp.aliyun.com
    username: xxx@aliyun.com
    password: xx
    default-encoding: UTF-8
#    热部署使用
  devtools:
    restart:
      additional-paths: /shiro-[\\w-\\.]+jar

# 用于检测文件上传下载位置用
dev-environment: dev




#  shiro-redis

shiro:
  loginUrl: /login
  successUrl: /index
  unauthorizedUrl: /index


# mybatis config

mybatis:
  # 数组配置
  mapper-locations:
    - classpath:mappers/**.xml
    - classpath:mappers/extend/**.xml
  type-aliases-package: work.eanson.dao
  configuration:
#  驼峰
    map-underscore-to-camel-case: true
#    日志
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# redis
redis:
  password: Root@123456
  dataBase: 1
  host: 47.109.23.108
  port: 6379
#客户端超时时间单位是毫秒 默认是2000
  timeout: 3000
  maxTotal: 150
#最大空闲数
  maxIdle: 20
#最小空闲数
  minIdle: 10
#最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  maxWaitMillis: 3000

  workerId: 1
  datacenterId: 1

# log
logging:
  file:
  # 输出到项目目录下
    name: logback.log
#  level:
#  request mapping
#    org.springframework.web: trace

# aliyun

aliyun:
  accessKeyId: L
  secret: c
  SignName: a
  TemplateCode: a


#################################### develop config : ###################################

---
spring:
  profiles: dev
  datasource:
    druid:
      url: jdbc:mysql://47.109.23.108:3306/minzuchess?characterEncoding=utf8&useSSL=false&serverTimezone=GMT&serverTimezone=Asia/Shanghai
      username: root
      password: Root@123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 20
      max-wait: 3000

server:
  port: 8088
logging:
  level:
   root: info
# 开发环境上传位置 IDEA就上传到target目录下
my:
  # 公开棋盘码 演示用
  public-code: Demo
  # 临时棋谱路径  每天定时会删除
  tmp-cheep-path: /static/cheep_/tmp
  # 公共棋谱相对于系统的相对路径
  public-cheep-path: /static/cheep_

   #  是否忽略登录注册验证码
  isIgnoreCheckCodeRegister: true

  # 头像上传相对于系统的绝对路径
  avatarUploadPath: /static/img/avatar


#################################### production config : ################################

---
spring:
  profiles: prod
  datasource:
      druid:
        url: jdbc:mysql:///minzuchess?characterEncoding=utf8&useSSL=false&serverTimezone=GMT&serverTimezone=Asia/Shanghai
        username: root
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        initial-size: 10
        max-active: 20
        max-wait: 3000
  devtools:
    livereload:
      enabled: false


server:
  port: 8081
logging:
  level:
    root: info

# 项目上线具体文件位置 需要nginx联动
my:
  # 公开棋盘码 演示用
  public-code: Demo
  # 临时棋谱路径  每天定时会删除
  tmp-cheep-path: /var/www/www.eanson.work/static/cheep_/tmp
  # 公共棋谱相对于系统的相对路径
  public-cheep-path: /var/www/www.eanson.work/static/cheep_/tmp

   #  是否忽略登录注册验证码
  isIgnoreCheckCodeRegister: true

  # 头像上传相对于系统的绝对路径
  avatar-upload-path: /var/www/www.eanson.work/static/img/avatar
